import { Crew, Paddler, Roster } from "../types";

export const samplePaddlers: Paddler[] = [
  {
    name: "Ryan",
    side: "both",
    weight: 150,
    power: 10,
    height: 180,
    id: "0",
  },
  {
    name: "Alex",
    side: "left",
    weight: 176,
    power: 10,
    height: 180,
    id: "1",
  },
  {
    name: "Samantha",
    side: "right",
    weight: 132,
    power: 10,
    height: 180,
    id: "2",
  },
  {
    name: "David",
    side: "both",
    weight: 195,
    power: 10,
    height: 180,
    id: "3",
  },
  {
    name: "Emily",
    side: "left",
    weight: 120,
    power: 10,
    height: 180,
    id: "4",
  },
  {
    name: "Jason",
    side: "right",
    weight: 163,
    power: 10,
    height: 180,
    id: "5",
  },
  {
    name: "Olivia",
    side: "both",
    weight: 144,
    power: 10,
    height: 180,
    id: "6",
  },
  {
    name: "Michael",
    side: "left",
    weight: 182,
    power: 10,
    height: 180,
    id: "7",
  },
  {
    name: "Sophia",
    side: "right",
    weight: 97,
    power: 10,
    height: 180,
    id: "8",
  },
  {
    name: "Ethan",
    side: "both",
    weight: 154,
    power: 10,
    height: 180,
    id: "9",
  },
  {
    name: "Isabella",
    side: "left",
    weight: 111,
    power: 10,
    height: 180,
    id: "10",
  },
  {
    name: "Daniel",
    side: "right",
    weight: 178,
    power: 10,
    height: 180,
    id: "11",
  },
  {
    name: "Mia",
    side: "both",
    weight: 136,
    power: 10,
    height: 180,
    id: "12",
  },
  {
    name: "Matthew",
    side: "left",
    weight: 199,
    power: 10,
    height: 180,
    id: "13",
  },
  {
    name: "Charlotte",
    side: "right",
    weight: 121,
    power: 10,
    height: 180,
    id: "14",
  },
  {
    name: "James",
    side: "both",
    weight: 171,
    power: 10,
    height: 180,
    id: "15",
  },
  {
    name: "Amelia",
    side: "left",
    weight: 138,
    power: 10,
    height: 180,
    id: "16",
  },
  {
    name: "Benjamin",
    side: "right",
    weight: 192,
    power: 10,
    height: 180,
    id: "17",
  },
  {
    name: "Harper",
    side: "both",
    weight: 115,
    power: 10,
    height: 180,
    id: "18",
  },
  {
    name: "Lucas",
    side: "left",
    weight: 167,
    power: 10,
    height: 180,
    id: "19",
  },
  {
    name: "Ella",
    side: "right",
    weight: 124,
    power: 10,
    height: 180,
    id: "20",
  },
  {
    name: "Henry",
    side: "both",
    weight: 142,
    power: 10,
    height: 180,
    id: "21",
  },
  {
    name: "Avery",
    side: "left",
    weight: 106,
    power: 10,
    height: 180,
    id: "22",
  },
  {
    name: "Jack",
    side: "right",
    weight: 185,
    power: 10,
    height: 180,
    id: "23",
  },
  {
    name: "Scarlett",
    side: "both",
    weight: 134,
    power: 10,
    height: 180,
    id: "24",
  },
  {
    name: "William",
    side: "left",
    weight: 193,
    power: 10,
    height: 180,
    id: "25",
  },
  {
    name: "Grace",
    side: "right",
    weight: 100,
    power: 10,
    height: 180,
    id: "26",
  },
  {
    name: "Liam",
    side: "both",
    weight: 159,
    power: 10,
    height: 180,
    id: "27",
  },
  {
    name: "Chloe",
    side: "left",
    weight: 109,
    power: 10,
    height: 180,
    id: "28",
  },
  {
    name: "Noah",
    side: "right",
    weight: 174,
    power: 10,
    height: 180,
    id: "29",
  },
];

export const sampleRoster: Roster = {
  id: "roster-0",
  name: "Roster 0",
  paddlers: samplePaddlers,
};

export const sampleCrew: Crew = {
  id: crypto.randomUUID(),
  name: "Sample Crew",
  roster: sampleRoster.paddlers,
  numRows: 10,
  centerMass: 5,
  leftSide: [],
  rightSide: [],
  drum: null,
  steer: null,
};
